[Main]
start_time = 2025-01-01 00:00:00
end_time = 2025-02-01 00:00:00
time_step = "01:00"
use_ukv = true

[Output]
folder = "some/random/path"

["OpenGHG Presets"."Domains"."EUROPE"]

["OpenGHG Presets"."Locations"."NPL"]

["Species"."Inert"]
category = "None"
molecular_weight = 1
deposition_velocity = 0
material_unit = "g"
uv_loss_rate = 0
half_life = "Stable"
