max_num_particles = 700000
max_num_full_particles = 2
max_num_puffs = 2
max_num_original_puffs = 2
skew_time = "00:00"
velocity_memory_time = "00:00"
mesoscale_velocity_memory_time = "00:00"
inhomogeneous_time = "00:00"
delta_opt = "1"
puff_time = "00:00"
sync_time = "00:03:00"
puff_interval = "00:10"
deep_convection = false
radioactive_decay = false
agent_decay = false
dry_deposition = false
wet_deposition = false
turbulence = true
mesoscale_motions = true
chemistry = false
